llm:
  openai:
    provider: openai
    model_name: gpt-3.5-turbo
    api_key_env: OPENAI_API_KEY
    temperature: 0.2
  groq:
    provider: groq
    model_name: llama3-3.2-90b-vision-preview
    api_key_env: GROQ_API_KEY
  groq_fast:
    provider: groq
    model_name: llama3-70b-8192
    api_key_env: GROQ_API_KEY

vector_store:
  index_path: ./vector_index
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  pdf_data_folder: data/pdfs

sql:
  db_type: mysql
  uri_env: MYSQL_URI
  tables:
    appointments: appointments 
    patients: patients
    admit: admit
    diagnosis: diagnosis
    prescriptions: prescription_medicines
    visits: visits
    nurses: nurses

database:
  host: localhost
  user: root
  password: DB_PASS
  database: hospital